spring.application.name=java-prac

spring.datasource.url=jdbc:postgresql://localhost:5432/java-prac-DB
spring.datasource.username=postgres
spring.datasource.password=6835
spring.datasource.driver-class-name=org.postgresql.Driver

spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

spring.jpa.open-in-view=false
server.port=8080